SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE therapists;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO therapists (therapist_id, therapist_name, specialization, email, description, profile_image, experience_years) VALUES
(1, 'Dr. Sarah Williams', 'Clinical Psychology & CBT', 'sarah.williams@example.com', 'Specialist in evidence-based cognitive behavioral therapy interventions for adult anxiety, panic disorders, and clinical depression.', 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300', 7),
(2, 'Dr. David Miller', 'CBT & Mood Disorders', 'david.miller@example.com', 'Focuses on helping patients identify cognitive distortions, manage obsessive-compulsive tendencies, and build positive behavioral habits.', 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300', 14),
(3, 'Dr. Jessica Taylor', 'Cognitive Restructuring Specialist', 'jessica.taylor@example.com', 'Experienced practitioner in structured cognitive behavioral therapy, targeting insomnia, social anxiety, and stress-related disorders.', 'https://images.unsplash.com/photo-1594824813573-246434de83fb?auto=format&fit=crop&q=80&w=300', 9),
(4, 'Dr. James Anderson', 'Anxiety & CBT Treatment', 'james.anderson@example.com', 'Dedicated to designing customized, goal-oriented CBT plans to assist clients in overcoming phobias, general anxiety, and academic stress.', 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300', 4),
(5, 'Dr. Emily White', 'Behavioral Activation Therapy', 'emily.white@example.com', 'Uses behavioral activation techniques within a CBT framework to treat depressive episodes and help clients find meaning in daily routines.', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300', 5),
(6, 'Dr. Richard Harris', 'PTSD & EMDR Therapy', 'richard.harris@example.com', 'A certified EMDR practitioner specializing in trauma resolution, post-traumatic growth, and treating chronic PTSD symptoms.', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300', 15),
(7, 'Dr. Lisa Cooper', 'Somatic Experiencing practitioner', 'lisa.cooper@example.com', 'Combines body-oriented trauma recovery methods with traditional psychotherapy to resolve deep-seated stress and trauma patterns.', 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?auto=format&fit=crop&q=80&w=300', 8),
(8, 'Dr. Robert Martin', 'Complex Trauma Specialist', 'robert.martin@example.com', 'Veteran therapist providing compassionate, trauma-informed care to individuals healing from complex developmental trauma and grief.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300', 3),
(9, 'Dr. Karen Nelson', 'Childhood Abuse Recovery', 'karen.nelson@example.com', 'Specializes in helping adult survivors of childhood abuse or neglect process past memories and establish secure relationship patterns.', 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&q=80&w=300', 7),
(10, 'Dr. Thomas King', 'Relational Trauma Therapy', 'thomas.king@example.com', 'Dedicated to helping individuals rebuild lives after domestic abuse, coercive relationships, and severe life-altering events.', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300', 7),
(11, 'Dr. Michael Brown', 'Systemic Family Dynamics', 'michael.brown@example.com', 'Focuses on structural family therapy, resolving communication breakdowns, and strengthening relationships within family systems.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300', 4),
(12, 'Dr. Susan Green', 'Marriage & Family Therapist', 'susan.green@example.com', 'Providing counseling to couples and families to help navigate marital conflict, life transitions, and co-parenting challenges.', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300', 8),
(13, 'Dr. William Scott', 'Parent-Teen Mediation', 'william.scott@example.com', 'Works closely with parents and teenagers to establish healthy boundaries, resolve conflicts, and improve domestic harmony.', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300', 3),
(14, 'Dr. Patricia Hall', 'Intergenerational Counseling', 'patricia.hall@example.com', 'Assists multi-generational households in understanding cultural differences, aligning expectations, and fostering empathy.', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=300', 14),
(15, 'Dr. Charles Baker', 'Divorce Mediation Counseling', 'charles.baker@example.com', 'Helps families navigate the emotional impact of divorce, working to keep child emotional health central during transitions.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300', 6),
(16, 'Dr. Evelyn Vance', 'Mindfulness-Based Stress Reduction (MBSR)', 'evelyn.vance@example.com', 'Combines traditional therapy with mindfulness practices, meditation training, and breathing exercises for daily stress management.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300', 13),
(17, 'Dr. Daniel Carter', 'Somatic Mindfulness Practice', 'daniel.carter@example.com', 'Integrates somatic mindfulness practices and deep breathing techniques to cultivate awareness, calm, and emotional resilience.', 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=300', 18),
(18, 'Dr. Nancy Adams', 'Zen Practices & Breathwork', 'nancy.adams@example.com', 'Focuses on applying Zen principles to modern mental health challenges, encouraging mindful acceptance and distress tolerance.', 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&q=80&w=300', 12),
(19, 'Dr. Paul Rivera', 'Mindful Self-Compassion Coaching', 'paul.rivera@example.com', 'Helps individuals combat negative self-talk and perfectionism by integrating self-compassion tools with therapeutic goals.', 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300', 12),
(20, 'Dr. Helen Clark', 'Holistic Wellness Psychologist', 'helen.clark@example.com', 'Experienced clinical psychologist incorporating holistic lifestyle assessments, meditation, and biofeedback techniques.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300', 19),
(21, 'Dr. Barbara Mitchell', 'Pediatric Behavior Analysis', 'barbara.mitchell@example.com', 'Specializes in early childhood behavioral analysis, supporting families with early signs of developmental differences and ADHD.', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300', 5),
(22, 'Dr. Joseph Perez', 'Child Play Therapy Specialist', 'joseph.perez@example.com', 'Uses structured play-based methodologies to help children express complex emotions, trauma, and relational anxieties.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300', 5),
(23, 'Dr. Sandra Roberts', 'Adolescent Psychology', 'sandra.roberts@example.com', 'Assisting pre-teens and teenagers in coping with peer pressure, social media anxieties, self-esteem, and mood fluctuations.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300', 9),
(24, 'Dr. Steven Gomez', 'Child Developmental Coaching', 'steven.gomez@example.com', 'Guides children with social communication disorders or sensory processing sensitivities to thrive in school environments.', 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=300', 15),
(25, 'Dr. Linda Turner', 'Neurodevelopmental Support', 'linda.turner@example.com', 'Supporting neurodiverse children and their parents in developing customized home schedules and behavioral coping skills.', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=300', 17);